name       : perl-text-diff
version    : 1.45
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEILB/Text-Diff-1.45.tar.gz : e8baa07b1b3f53e00af3636898bbf73aec9a0ff38f94536ede1dbe96ef086f04
license    :
    - Artistic-1.0-Perl
    - GPL-2.0
component  : programming.perl
summary    : Text::Diff - Perform diffs on files and record sets
description: |
    Text::Diff - Perform diffs on files and record sets
builddeps  :
    - perl-algorithm-diff
rundeps    :
    - perl-algorithm-diff
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
